// generated from users/manna-harbour_miryoku/miryoku.org  -*- buffer-read-only: t -*-

#include "manna-harbour_miryoku.h"

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [BASE] = LAYOUT_miryoku(
    KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, 
    KC_A, KC_S, KC_D, KC_F, KC_G, LT(MBO,KC_H), KC_J, KC_K, KC_L, KC_SCLN, 
    LSFT_T(KC_Z), KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, RSFT_T(KC_SLSH), 
    KC_NP, KP_NP, LALT_T(KC_ESC), LT(NAVR,KC_LGUI), LCTL_T(KC_TAB), KC_SPC, LT(MOUR,KC_BSPC), RALT_T(KC_ENT), KC_NP, KC_NP),
  [NAVR] = LAYOUT_miryoku(
    KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, 
    KC_LGUI, KC_TAB, KC_NO, KC_F, KC_NO, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_QUOT,   
    KC_LSFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_MPLY, KC_VOLD, KC_VOLU, KC_DOT, KC_DQUO, 
   KC_NP,  KC_NP,LALT_T(KC_ESC), KC_NO, LCTL_T(KC_TAB),  KC_SPC, KC_BSPC, RALT_T(KC_ENT), KC_NP, KC_NP
  ),
  [MOUR] = LAYOUT_miryoku(
    KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, 
    KC_GRV, KC_TILD, KC_NO, KC_NO, KC_NO, KC_UNDS, KC_LCBR, KC_RCBR, KC_MINS, KC_PLUS, 
    KC_LSFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_PIPE, KC_LBRC, KC_RBRC, KC_BSLS, KC_EQL, 
   KC_NP,  KC_NP,LALT(KC_ESC), KC_NO, LCTL_T(KC_TAB), KC_SPC, KC_BSPC, RALT(KC_ENT), KC_NP, KC_NP
  ), 
  [MBO] = LAYOUT_miryoku(
    KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10,
    KC_F11, KC_F12, KC_F13, KC_F14, KC_F15, KC_BTN2, KC_BTN2, KC_BTN3, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_BTN3, KC_TRNS, KC_TRNS,
    KC_NP,   KC_NP,   KC_TRNS, KC_TRNS, KC_TRNS, KC_BTN1, KC_BTN2, KC_BTN3, KC_NP,   KC_NP
  )
};
